parameters:
    csvwriter.service.class: Xola\ReportWriterBundle\Service\CSVWriter
    excelwriter.service.class: Xola\ReportWriterBundle\Service\ExcelWriter
    phpexcel.class:  Xola\ReportWriterBundle\SpreadsheetFactory

services:
    csvwriter:
        class: "%csvwriter.service.class%"
        arguments: [ "@logger" ]
        tags:
              - { name: monolog.logger, channel: csvwriter }

    excelwriter:
        class: "%excelwriter.service.class%"
        arguments: [ "@logger", "@phpexcel" ]
        tags:
              - { name: monolog.logger, channel: excelwriter }

    phpexcel:
        class: "%phpexcel.class%"
